name: "fibertoolsrs_extract"
description: Extract Fiber-seq data into plain text files
keywords:
- methylation
- genomics
- bam
- m6A
- fiberseq
tools:
- "fibertoolsrs":
    description: "Mitchell Vollger's rust tools for fiberseq data."
    homepage: "https://fiberseq.github.io/fibertools/fibertools.html"
    documentation: "https://fiberseq.github.io/fibertools/fibertools.html"
    tool_dev_url: "https://github.com/fiberseq/fibertools-rs"
    doi: "10.5281/zenodo.14782951"
    licence: ['MIT']
    identifier: ""

input:
- - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1' ]`
  - bam:
      type: file
      description: Sorted BAM/CRAM file
      pattern: "*.{bam,cram}"
      ontologies:
      - edam: "http://edamontology.org/format_2572"     # BAM
      - edam: "http://edamontology.org/format_2573"     # CRAM

output:
  bed:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - '*.bed':
        type: file
        description: bedMethyl output file(s)
        pattern: "*.bed"
        ontologies: []
  versions:
  - versions.yml:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
      ontologies:
      - edam: "http://edamontology.org/format_3750"     # YAML

authors:
- "@mrvollger"
maintainers:
- "@mrvollger"
